---

 - name: Install Metricbeat on Webservers
   hosts: webservers
   remote_user: azadmin
   become: true
   tasks:

     - name: copy Metricbeat installer to VM
       copy:
         src: /etc/ansible/metricbeat-7.4.0-amd64.deb
         dest: /var/cache/apt/archives

     - name: download Metricbeat
       command: sudo dpkg -i /var/cache/apt/archives/metricbeat-7.4.0-amd64.deb

     - name: copy Metricbeat config
       copy:
         src: /etc/ansible/metricbeat.yml
         dest: /etc/metricbeat/metricbeat.yml

     - name: enable Metricbeat
       command: metricbeat modules enable docker
     
     - name: run Metricbeat setup
       command: metricbeat setup

     - name: run Metricbeat command
       command: sudo service metricbeat start

     - name: enable Metricbeat on boot
       systemd:
         name: metricbeat
         enabled: yes
